Implement error handling in setup_dwm script
Add error handling function and trap for errors during installation.

diff --git a/setup_dwm b/setup_dwm
--- a/setup_dwm
+++ b/setup_dwm
@@ -36,6 +36,13 @@ clear
 ##################################################################################################
 #################################### INSTALL BASE APPS ###########################################
 ##################################################################################################
+error_handler() {
+    echo ""
+    echo "An error occurred. Press Enter to continue..."
+    read
+}
+
+trap 'error_handler' ERR
 
 sudo pacman -Syu fish eza fastfetch git vim neovim gcc make base-devel pkgconf xorg xorg-xinit feh gxmessage sxiv python-pywal terminus-font ttf-mononoki-nerd noto-fonts-emoji \
 lightdm lightdm-gtk-greeter openssh firefox qutebrowser mousepad figlet sxhkd slock dunst xwallpaper calcurse
